version: "2.4"

services:
  secondary-dns:
    image: sausix/bind-sql-base-alpine:nopython-latest
    container_name: secondary-dns
    restart: always
    networks:
      - bind-secondary
    ports:
# Bind on all interfaces
      - "53:53/tcp"
      - "53:53/udp"
# Or bind to public interfaces only:
#      - "${IP_PUB}:53:53/tcp"
#      - "${IP_PUB}:53:53/udp"
#      - "${IP6_PUB}:53:53/tcp"
#      - "${IP6_PUB}:53:53/udp"
# Optional rndc access from host
#      - "127.0.0.1:953:953/tcp"
    environment:
      - TZ=${TZ:-}
      - PRIMARY=192.168.51.10
      - PRIMARY_ZONES=example.com,example2.com
    tmpfs:
      - /etc/bind
      - /var/named
    volumes:
      - ./bind-config:/container/bind-config:ro
      - ./init.d:/container/init.d:ro
    command: ["/usr/local/sbin/named", "-g", "-u", "named"]
#    command: ["/usr/local/sbin/named", "-f", "-u", "named", "-L", "/var/log/bind/bind.log"]

networks:
  bind-secondary:
    name: bind-secondary
#    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: br_bind_sec
