#!/bin/sh -e

# PRIMARY=192.168.16.2
# PRIMARY_ZONES=example.com,example2.com

INCLUDE="/etc/bind/named.local-gen.conf"

if [ "${GENERATE_ZONES}" = "no" ]; then
	echo "Disabled by env GENERATE_ZONES='no'."
	echo "# Disabled by env GENERATE_ZONES='no' in generate-zones-from-env.sh" > "$INCLUDE"
	exit 0
fi

if [ -z "$PRIMARY" ]; then
	echo "Missing env 'PRIMARY' which is requires as zone transfer source." >&2
	echo "# Disabled due to error in generate-zones-from-env.sh" > "$INCLUDE"
	exit 1
fi

if [ -z "$PRIMARY_ZONES" ]; then
	echo "Missing env 'PRIMARY_ZONES' which is requires as list of zones to acquire." >&2
	echo "# Disabled due to error in generate-zones-from-env.sh" > "$INCLUDE"
	exit 1
fi


echo "# Generated by 'generate-zones-from-env.sh'" > "$INCLUDE"

# Define masters value
split_primary ()
{
	IFS=','
	echo -n " "
	for HOST in $1; do
		echo -n "${HOST}; "
	done
}
PRIMARY_STR=$(split_primary "${PRIMARY}")


# Loop through zones
split_zones ()
{
	IFS=','
	for ZONE in $1; do
		echo "
zone \"${ZONE}\" {
	type secondary;
	file \"${ZONE}.db\";
	masters {$2};
};
"
	done
}
split_zones "${PRIMARY_ZONES}" "${PRIMARY_STR}" >> "$INCLUDE"


# TODO: rndc approach?

echo "Done."
exit 0
